name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
        with:
           go-version-file: go.mod
      - name: Run Tests
        run: make test:ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
